#ItemCommandRepair by Shadowlauch
##
#The price is based on the ratio and the durability.
#Example: Diamond-Pickaxe: 0.06*1562~90 
##
#Durabilities: 
# Iron: 251 	
# Diamond: 1562 
#
#The Ratio format should look like this: x.xx (example: 0.01)
##


ratios:
  diamond:
    pickaxe: 0.06
    axe: 0.06
    shovel: 0.02
    sword: 0.03
    hoe: 0.03
  iron:
    pickaxe: 0.03
    axe: 0.03
    shovel: 0.01
    sword: 0.02
    hoe: 0.02
  gold:
    pickaxe: 0.06
    axe: 0.06
    shovel: 0.02
    sword: 0.03
    hoe: 0.03
  stone:
    pickaxe: 0.006
    axe: 0.006
    shovel: 0.002
    sword: 0.003
    hoe: 0.003
  others:
    shears: 0.02
  armor:
    chain:
      helmet: 0.1
      chestplate: 0.13
      leggings: 0.11
      boots: 0.08 
    iron:
      helmet: 0.4
      chestplate: 0.8
      leggings: 0.6
      boots: 0.2
    gold:
      helmet: 0.8
      chestplate: 1.5
      leggings: 1.3
      boots: 0.5
    diamond:
      helmet: 0.8
      chestplate: 1.5
      leggings: 1.3
      boots: 0.5
    


#You can edit templates freely.
#But you have to include the variable.
#You can use the followiing colors, you have to put the colors in "<>" for example: <gray>
#<black>, <darkblue>, <darkgreen>, <darkaqua>, <darkred>, <darkpurple>, <gold>, <gray>, <darkgray>, <blue>, <green>, <aqua>, <red>, <lightpurple>, <yellow>, <white>
#U can use it like this: <white>Hi <purple>this is a <gray>test.
#DO NOT USE NORMAL MINECRAFT COLOR CODES!
templates:
  info:
    repaired: You have repaired your Tool/Sword for &pr.
    priceinfo: You have to pay &pr to repair your Tool/Sword.
  errors:
    notenoughmoney: You do not have enough money.
    notneedtorepair: Your Tool/Sword does not require a repair.
    nopermissions: You do not have the permission to do that.